name: dart_helper_utils
description: This package offers a collection of Dart utilities, tools for converting dynamic objects to various types, and extending core Dart classes with extensions.
repository: https://github.com/omar-hanafy/dart_helper_utils
version: 6.0.0-dev.2

topics:
  - utils
  - utilities
  - helpers
  - extensions-pack
  - case-conversion

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  async: ^2.13.0
  collection: ^1.19.1
  convert_object: 1.0.0
  equatable: ^2.0.7
  intl: ">=0.19.0 <1.0.0"
  meta: ^1.17.0
  mime: ^2.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.28.0
